port: 4000
permalink: /:categories/:year/:month/:title.html
exclude: ['README.md']
markdown: redcarpet
assets:
  cachebust: none
  gzip: true
  sources:
    - _assets/js
    - _assets/css
    - _assets/img
  compress:
    css: 'sass'
    js: 'uglifier'